SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP SCHEMA IF EXISTS `XY_POI` ;
CREATE SCHEMA IF NOT EXISTS `XY_POI` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `XY_POI` ;

-- -----------------------------------------------------
-- Table `XY_POI`.`POI`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `XY_POI`.`POI` ;

CREATE TABLE IF NOT EXISTS `XY_POI`.`POI` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL,
  `POSITION_X` BIGINT NOT NULL,
  `POSITION_Y` BIGINT NOT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `POSITION` (`POSITION_X` ASC, `POSITION_Y` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO POI
VALUES(null, 'Lanchonete', 27, 12, NOW());

INSERT INTO POI
VALUES(null, 'Posto', 31, 18, NOW());

INSERT INTO POI
VALUES(null, 'Joalheria', 15, 12, NOW());

INSERT INTO POI
VALUES(null, 'Floricultura', 19, 21, NOW());

INSERT INTO POI
VALUES(null, 'Pub', 12, 8, NOW());

INSERT INTO POI
VALUES(null, 'Supermercado', 23, 6, NOW());

INSERT INTO POI
VALUES(null, 'Churrascaria', 28, 2, NOW());
