spring:
    datasource:
        url: jdbc:mysql://localhost:3306/xy_poi
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        max-wait: 10000
        max-active: 30
        test-on-borrow: true
        validation-query: SELECT 1
    jpa:
        show_sql: true
        hibernate:
            ddl-auto: none